name: s_dropdown
description: "Flexible, lightweight Flutter dropdown (SDropdown) with precise overlay control, keyboard navigation, controller-based actions, item-specific styling, and responsive sizing."
license: MIT
issue_tracker: https://github.com/SoundSliced/s_dropdown/issues
repository: https://github.com/SoundSliced/s_dropdown
version: 3.0.0
homepage: https://github.com/SoundSliced/s_dropdown

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
